version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "electron"
      - dependency-name: "electron-builder"
      - dependency-name: "sass"
    open-pull-requests-limit: 20
