/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAccountMenu: typeof import('./app/components/AppAccountMenu.vue')['default']
    AppCard: typeof import('./app/components/AppCard.vue')['default']
    AppDialog: typeof import('./app/components/AppDialog.vue')['default']
    AppDrawer: typeof import('./app/components/AppDrawer.vue')['default']
    AppNetworkError: typeof import('./app/components/AppNetworkError.vue')['default']
    AppPage: typeof import('./app/components/AppPage.vue')['default']
    AppPageHeader: typeof import('./app/components/AppPageHeader.vue')['default']
    AvatarChip: typeof import('./app/components/AvatarChip.vue')['default']
    DashboardHeader: typeof import('./app/components/headers/DashboardHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCreateDialog: typeof import('./app/components/dialogs/UserCreateDialog.vue')['default']
    UserHeader: typeof import('./app/components/headers/UserHeader.vue')['default']
    VInput: typeof import('./app/components/inputs/VInput.vue')['default']
    VSelect: typeof import('./app/components/inputs/VSelect.vue')['default']
  }
}
