FROM node:18-alpine as build

WORKDIR /app

COPY ./apps/web /app/apps/web
COPY ./packages /app/packages
COPY ./turbo.json /app/turbo.json
COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock

RUN yarn install
RUN yarn web:build

FROM nginx:stable-alpine as runtime

COPY --from=build /app/apps/web/dist /usr/share/nginx/html
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
