version: "3.8"

services:
  api:
    container_name: turbo-starter-api
    image: dhivinx/turbo-starter-api:0.0.1-local
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile.local
    env_file:
      - .env.local
    ports:
      - ${API_HTTP_PORT}:${API_HTTP_PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/api/dist
      - /app/packages/config/node_modules
    restart: always

  web:
    container_name: turbo-starter-web
    image: dhivinx/turbo-starter-web:0.0.1-local
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile.local
    env_file:
      - .env.local
    ports:
      - 8080:8080
    depends_on:
      - api
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/packages/config/node_modules
    restart: always

  postgres:
    container_name: turbo-starter-postgres
    image: postgres
    env_file:
      - .env.local
    ports:
      - '5433:${DATABASE_PORT}'
    volumes:
      - turbo-starter-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped

volumes:
  turbo-starter-postgres-data:


